version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: auff-ups
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: cloudinary
    versions:
    - 1.23.0
    - 1.24.0
    - 1.25.0
  - dependency-name: react-dropzone
    versions:
    - 11.2.4
    - 11.3.0
    - 11.3.1
  - dependency-name: react-jss
    versions:
    - 10.5.1
